CREATE TABLE IF NOT EXISTS `cards` (
    `id` BINARY(16) NOT NULL PRIMARY KEY,
    `name` VARCHAR(50) NOT NULL,
    `description` VARCHAR(50) NOT NULL,
    `points` INT NOT NULL

)ENGINE=InnoDB DEFAULT CHARSET=UTF8MB4;
