# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Deploy with rsync
      # StrictHostKeyChecking=no is not the best way to do it, but trying to add VPS_IP into
      # the known_hosts file just kept failing. All scripts tried to use the ssh-keyscan command
      # which is the source of failures.
      run: rsync -avz 'ssh -o StrictHostKeyChecking=no -p 1337' ./target/ ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:/home/nspe/target
      
