# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ devops ]
  pull_request:
    branches: [ devops ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn -B package --file pom.xml ; pwd ; ls -l
    - name: SSH Server Deploy
      uses: kostya-ten/ssh-server-deploy@v4
      with:
        host: ${{ secrets.VPS_IP }}
        port: ${{ secrets.VPS_PORT }}
        username: ${{ secrets.VPS_USER }}
        private_key: ${{ secrets.SSH_PRIVATE_KEY_NA_VPS }}
        scp_source: target/
        scp_target: ~/
        before_script: |
          df -h
        after_script: |
          whoami
