# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ devops, develop, main ]
  pull_request:
    branches: [ devops, develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout backend repo
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Download Unity game artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.ACCESS_TOKEN}}
        workflow: unity_build.yml 
        branch: devops
        name: unity_webgl_latest
        path: src/main/resources/public
        repo: Group-9-Semester-4/ninja-game
    - name: Check files
      run: cd $GITHUB_WORKSPACE/src/main/resources/public ; ls -laf 
    - name: Build with Maven
      run: mvn -B package -P prod --file pom.xml ; pwd ; ls -l      
    - name: rsync deployments
      uses: burnett01/rsync-deployments@4.1
      with:
        switches: -avzr --delete
        path: target/
        remote_path: ~/target
        remote_host: ${{ secrets.VPS_IP }}
        remote_port: ${{ secrets.VPS_PORT }}
        remote_user: ${{ secrets.VPS_USER }}
        remote_key: ${{ secrets.VPS_PRIVATE_KEY }}
